### ISSUE TITLE
请问一下合约中的类型

### ISSUE THREAD

**Issue by freshgeek** [kpyaoqi/voting-truffle#1]
你这边使用的是bytes2 
教程中使用的是bytes32

然后传参部署执行后，出现：

```


Error: invalid arrayify value (argument="value", value="Alice00000000000000000000000000000000000000000000000000000000000", code=INVALID_ARGUMENT, version=bytes/5.7.0)
    at evalmachine.<anonymous>
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'invalid arrayify value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: 'Alice00000000000000000000000000000000000000000000000000000000000',
  hijackedStack: 'Error: invalid arrayify value (argument="value", value="Alice00000000000000000000000000000000000000000000000000000000000", code=INVALID_ARGUMENT, version=bytes/5.7.0)\n' +
    '    at Logger.makeError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/logger/lib.esm/index.js:224:1)\n' +
    '    at Logger.throwError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/logger/lib.esm/index.js:233:1)\n' +
    '    at Logger.throwArgumentError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/logger/lib.esm/index.js:236:1)\n' +
    '    at arrayify (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/bytes/lib.esm/index.js:90:1)\n' +
    '    at FixedBytesCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/fixed-bytes.js:15:28)\n' +
    '    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/array.js:57:1\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at pack (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/array.js:43:1)\n' +
    '    at TupleCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/tuple.js:51:20)\n' +
    '    at AbiCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/abi-coder.js:86:1)\n' +
    '    at ABICoder.encodeParameters (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth-abi/lib/index.js:127:1)\n' +
    '    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth-contract/lib/index.js:463:1\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at Object._encodeMethodABI (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth-contract/lib/index.js:462:6)\n' +
    '    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:215:1\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}
```

**Comment by kpyaoqi** [comment]
这个的话是你合约中用的是byte几，就需要传入多少的字节，如果有什么问题可以直接加我微信。
